--- 
- name: My Test playbook
  hosts: webservers
  become: true
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: installed
  - name: Started httpd service
    service:
      name: httpd
      state: started
